security:
- name: unpriveleged
  description: Does not use security context priveleged
  kind: Pod
  field: .spec.containers[*].securityContext.privileged
  operator: unset
  valueType: string
operations:
- name: app-label
  description: Includes a label with key "app"
  kind: Pod
  field: .metadata.labels.app
  operator: set
  valueType: string
- name: name-regex
  description: Includes a name with cd-
  kind: Pod
  field: .metadata.name
  operator: matches
  value: "cd-.*"
  valueType: string
performance:
- name: limit-set
  description: Has resource requests set
  kind: Pod
  field: .spec.containers[0].resources.requests.cpu
  operator: set
  valueType: string
