apiVersion: v1
kind: Pod
metadata:
  name: redis-django
  labels:
    app: web
spec:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  containers:
    - name: key-value-store
      image: redis
      ports:
        - containerPort: 6379